version: 0.2

env:
  variables:
    DATABASE_URL: "sqlite:////nothotdog.sqlite"
    SECRET_KEY: "fakesecretforrunningtests"

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends postgresql-client
      - pip install -r requirements.txt
      - rm -rf /var/lib/apt/lists/*
  build:
    commands:
      - echo Tests started on `date`
      - python manage.py test
  post_build:
    commands:
      - echo Tests completed on `date`